<a href="https://colab.research.google.com/github/leenago/NLP_edu/blob/master/200903_BoW_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#BoW 구현

In [1]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 원숭이에게 사과를 줬어']

In [2]:
doc_list = []

for doc in docs:
  doc_list.append(doc.split(' '))

doc_list

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [3]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id)) #중복값 방지가 가능한 이유: defaultdict

In [4]:
for doc in doc_list:
  for token in doc:
    word2id[token]

word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '먹이를': 6,
             '보고': 4,
             '사과를': 8,
             '오늘': 0,
             '원숭이를': 3,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리': 2})

In [5]:
import numpy as np
bag_of_words = []
for i, doc in enumerate(doc_list):
  bow = np.zeros(len(word2id), dtype = int)
  print(bow)


  for token in doc:   #첫번째 문장에서 단어 하나하나 for문
    bow[word2id[token]] += 1
  bag_of_words.append(bow.tolist())

bag_of_words

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [6]:
from IPython.core import display as ICD
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [7]:
vocab = []
for v in sorted_vocab:
  vocab.append(v[1])
print('vocab', vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [8]:
for i in range(len(docs)):
  print('문서{} : {}'.format(i,docs[i])) #format 처리를 하면 i가 {}에 들어가게 된다. docs[i]는 : 뒤의 {}에
  ICD.display(pd.DataFrame([bag_of_words[i]], columns = vocab))
  print('\n\n') #\n\n은 문서0과 문서1 사이의 엔터

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

#단어의 순서를 고려하지 않은 BoW

In [9]:
docs= ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
       '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [10]:
doc_list = []

for doc in docs:
  doc_list.append(doc.split(' '))

doc_list

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [11]:
from collections import defaultdict
word2id = defaultdict(lambda :len(word2id))

In [12]:
word2id

defaultdict(<function __main__.<lambda>>, {})

In [13]:
for doc in doc_list:
  for token in doc:
    word2id[token]

word2id

defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [14]:
import numpy as np

bag_of_chickens = []
for i, doc in enumerate(doc_list):
  bow = np.zeros(len(word2id), dtype = int)

  for token in doc:
    bow[word2id[token]] += 1
  bag_of_chickens.append(bow.tolist())

bag_of_chickens

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [15]:
sorted_words = sorted((value, key) for key, value in word2id.items())
print('sorted_words: ', sorted_words)

sorted_words:  [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [16]:
vocab = []

for v in sorted_words:
  vocab.append(v[1])

vocab

['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']

In [17]:
for i in range(len(docs)):
  print('문서{} : {}'.format(i,docs[i])) #format 처리를 하면 i가 {}에 들어가게 된다. docs[i]는 : 뒤의 {}에
  ICD.display(pd.DataFrame([bag_of_chickens[i]], columns = vocab))
  print('\n\n') #\n\n은 문서0과 문서1 사이의 엔터

문서0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

#Bow - Sklearn

In [27]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [28]:
#토큰빈도계산: CounterVectorizer

from sklearn.feature_extraction.text import CountVectorizer

#선언
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
print(BoW.toarray())

vocab = count_vect.get_feature_names()
print(vocab)

[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [29]:
from IPython.core import display as ICD
import pandas as pd

for i in range(len(docs)):
  ICD.display('문서{}:{}'.format(i,docs[i]))
  print('\n')
  df = pd.DataFrame([BoW.toarray()[i]], columns = vocab)
  print(df)
  print('\n\n')


'문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어'



   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2





'문서1:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어'



   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2





#BoW - gensim
- 토큰화를 먼저 시켜주고
- Dictionary에 넣어준다
- 토큰화 된 리스트에 doc2bow 처리를 해준다.

In [30]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [31]:
from gensim import corpora

doc_list = []
for doc in docs:
  doc_list.append(doc.split())

doc_list

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘',
  '동물원에서',
  '코끼리',
  '원숭이를',
  '보고',
  '코끼리',
  '원숭이에게',
  '먹이를',
  '줬어',
  '오늘',
  '동물원에서',
  '원숭이에게',
  '사과를',
  '줬어']]

In [32]:
id2word = corpora.Dictionary(doc_list)
print(id2word)

Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


In [33]:
BoW = []
for doc in doc_list:
  BoW.append(id2word.doc2bow(doc))

BoW

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [34]:
#시각화

from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd

vocab = [id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
  print('문서{}:{}'.format(i, docs[i]))
  ICD.display(pd.DataFrame([sparse2full(BoW[i], len(vocab))], columns=vocab))
  print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0




문서1:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    2.0  1.0  1.0  2.0   1.0    2.0  2.0  2.0  1.0